### ISSUE TITLE
Remove optional tags

### ISSUE THREAD

**Issue by jamonholmgren** [KeenRivals/bestmotherfucking.website#11]
I have no idea if this is a good idea.

But Google seems to think it is: https://google.github.io/styleguide/htmlcssguide.xml?showone=Optional_Tags#Optional_Tags

![image](https://cloud.githubusercontent.com/assets/1479215/19371986/b25441f4-916c-11e6-8b9b-6211eb1849d6.png)

What do you think?

**Comment by KeenRivals** [comment]
That's very interesting. I did not know that was permitted! It would save 112 bytes if I remove the tags and re-indent the code. Compression nullifies some of those savings. A quick test with gzip shows that removing the tags saves 26 bytes.

| File | Bytes |
| --- | --- |
| full-html.html | 5241 |
| minimal.html | 5129 |
| full-html.html.gz | 2375 |
| minimal.html.gz | 2349 |

I don't think it would be _wrong_, but not having all of the tags triggers some sort of OCD in me. I want this site to be an example of good code, and stripping the tags just feels too weird.

**Comment by KeenRivals** [comment]
I forgot to add, that if I wanted to save a lot of bytes I could minify the HTML, but I want to keep it readable and I figure compression removes most overhead from whitespace.

**Comment by jamonholmgren** [comment]
Yeah, very tiny amount of savings. :) I just saw this the other day and thought of your website. It's interesting that Google thinks this is the way to go. Seems "wrong" to me but I started coding web pages 12 years ago.

**Comment by KeenRivals** [comment]
I appreciate the thought! I think I might warm up to it over time. I'm already using this trick in a few one-off sites just because. Thank you for informing me!

**Comment by jamonholmgren** [comment]
No worries, my pleasure. 😁
