### ISSUE TITLE
line-height is better unitless

### ISSUE THREAD

**Issue by bucklereed** [KeenRivals/bestmotherfucking.website#16]
Unitful line-height (which includes percentages; isn't it nice when CSS makes sense?) has tricky behaviour with cascading, and is best avoided since unitless line-height Just Works. [MDN has an example.](https://developer.mozilla.org/en/docs/Web/CSS/line-height#Prefer_unitless_numbers_for_line-height_values) This doesn't actually matter directly to such an awesome motherfucking website, which is too awesome to have complicated nesting and style interactions, but, in so far as it's the best motherfucking website on the goddamn interwebs, it'd be better if it was a showroom for relevant best practices.

**Comment by KeenRivals** [comment]
This is a very interesting quirk of CSS that I wasn't aware of. Thanks for pointing it out. I'll fix it here shortly.

> it's the best motherfucking website on the goddamn interwebs, it'd be better if it was a showroom for relevant best practices.

Thank you, that's my goal. 👍
