### ISSUE TITLE
<section> does nothing, but not enough nothing

### ISSUE THREAD

**Issue by bucklereed** [KeenRivals/bestmotherfucking.website#17]
Right now, bestmotherfucking.website has a mixture of `<section>` and numbered heading elements for hierarchy. It *could* be using `<section>` elements within `<section>`, which is the utopian HTML5 dream. If `<section>` was really adding value, this would be preferable. But, browsers basically ignore `<section>` and HTML5 outlining: apparently there are silly interactions with screenreaders which mean that they're probably never actually going to be used by browsers; there are probably other web-compat issues freezing this non-behaviour in place now too.

Since proper use of numbered heading elements will unambiguously structure the document and hence don't lose any semantic value, even if it's error-prone and obviously clunky, I would suggest giving up the pretence that HTML5 outlines are coming and removing the no-op and not-everywhere-they-could-be `<section>` tags.

**Comment by KeenRivals** [comment]
That's an interesting point. Is there some method I can validate what the document's outline is? So far I've found [HTML5 Outliner](https://gsnedders.html5.org/outliner/) which gives a weird result on bmfw. Looking for second opinions, or some suggestion for how exactly the best motherfucking website should outline its content.

**Comment by bucklereed** [comment]
[The Nu Validator](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fbestmotherfucking.website) will expose the outline according to the HTML5 outline algorithm, with the right checkbox ticked.

**Comment by KeenRivals** [comment]
Thanks. I think I like the sections from a structural OCD standpoint, but are they really doing nothing at all? I was under the impression that they added some semantic meaning to the document outline.

**Comment by bucklereed** [comment]
Sort of, but not really. Untitled `<section>`s mean something different in the outlining algorithm to what you'd get if you removed their tags, and that's not actually something you can express without them; if those are critical semantic information, you can't do without, but (IMO and IME) that's a vanishingly rare situation. If the outlining algorithm is in play, you can express the structure using just `<section>` and `<h1>` for titles, which is nice and pleasing--except you'd still have to use `<h2>` in second-level sections and `<h3>` etc similarly anyway for graceful degradation in UAs that didn't implement the outlining algorithm.

You can check that, as is, the sectioning elements aren't actually doing anything in terms of the outline structure by selecting 'text input', pasting in the source and stripping them out, and verifying that you get the same outline; this is basically the point of the outlining algorithm, which translates properly-used HTML 4.01-style numbered headings into a nice tree.

**Comment by KeenRivals** [comment]
Thank you for the insight. I think you're right that removing the sections is the best solution.
