### ISSUE TITLE
Your meme website is broken

### ISSUE THREAD

**Issue by The-King-of-Toasters** [KeenRivals/bestmotherfucking.website#25]
Just letting you know that cloudflare throws `Error 526: Invalid SSL certificate` when navigating to your website.

**Comment by KeenRivals** [comment]
Thanks a ton for letting me know. I've got the back end using a Cloudflare cert with 15-year expiry now. If things look good on your side we can close this. I was seeing a bit of weirdness relating to caching for a while because I'd temporarily toggled Cloudflare proxying.

**Comment by The-King-of-Toasters** [comment]
It lives!

Also, thanks for actually making this. Out of all of the *fuckingwebsites, I think yours is the best. it inspired me to go ahead and make my own, based off your template.
