### ISSUE TITLE
Prevent overscroll by adding overflow-wrap

### ISSUE THREAD

**Issue by Brixy** [KeenRivals/bestmotherfucking.website#29]
How about adding `overflow-wrap: break-word;` or `overflow-wrap: anywhere;` to the body selector. It would prevent overscroll by breaking long words and URLs—particularly on small screens.

**Comment by KeenRivals** [comment]
I don't see anywhere the default wrapping is misbehaving. I tested with a 260px viewport and it seems okay. I don't want to add more CSS unless there's an obvious benefit. If you screenshot an instance where wrapping is bad I'll add the CSS.

**Comment by Brixy** [comment]
Thanks for your comments.

Sorry—I was not precise enough. It’s not a problem with your site.

As browsers’ default heading font sizes are pretty large, I regularly have problems e.g. with longish German words in headings.

`overflow-wrap: break-word` is just a very easy way to solve this problem completely without tweaking font sizes using media queries.
