### ISSUE TITLE
Use www

### ISSUE THREAD

**Issue by waluigispear** [KeenRivals/bestmotherfucking.website#30]
https://www.yes-www.org/why-use-www/

**Comment by KeenRivals** [comment]
Their arguments for www do not apply to this meme website:

* We don't use cookies at all.
* CNAME stuff does not apply because the DNS host (cloudflare) does [CNAME flattening](https://support.cloudflare.com/hc/en-us/articles/200169056-Understand-and-configure-CNAME-Flattening).
