### ISSUE TITLE
The "revised font stack" link is broken

### ISSUE THREAD

**Issue by JobLeonard** [KeenRivals/bestmotherfucking.website#4]
http://www.awayback.com/revised-font-stack/

Here's a random but functioning archive.org link to it:

https://web.archive.org/web/20150303130927/http://www.awayback.com/revised-font-stack

**Comment by KeenRivals** [comment]
Ah, man that makes me sad. It was a good resource. Link rot cuts deep. I'll try to find an alternative that gets the idea across. If you have any idea of an alternative I'd appreciate it.

**Comment by JobLeonard** [comment]
Isn't an archive.org snapshot an acceptable alternative?

**Comment by KeenRivals** [comment]
That's a good point. I'll use that for now.

**Comment by JobLeonard** [comment]
Note that this results in a link from the archive.org Wayback machine to a website formerly hosted on awayback.com

**Comment by anarcat** [comment]
the original site works here now, in case you want to revert back to the real thing.

**Comment by KeenRivals** [comment]
@anarcat Thank you for informing me, I will revert.

**Comment by aykevl** [comment]
It looks like the right URL is:
http://www.awayback.com/index.php/2010/02/03/revised-font-stack/

The current link just points to a list of recent posts.

**Comment by KeenRivals** [comment]
@aykevl, thank you for letting me know. I've updated the URL.  awayback.com seems to be having a few issues lately.
