### ISSUE TITLE
FF Reader mode tip

### ISSUE THREAD

**Issue by jtagcat** [KeenRivals/bestmotherfucking.website#41]
So I'm not sure on the language, but:

Ever fucking noticed ![image](https://design.firefox.com/icons/icons/desktop/reader-mode-16.svg) in Firefox's URL bar?

This is the button for [reader view](https://blog.mozilla.org/firefox/reader-view/). Click it, it fucks websites to be better.

(Ironically this website doesn't support it, because it's already good enough.) (no idea why)

**Comment by KeenRivals** [comment]
I use Firefox's reader mode frequently.  I wonder why it doesn't offer it for bmfw, although I suppose it doesn't have much to do to it other change colors/margins. 

I appreciate the thought but I'm not sure this behavior is worth a section on bmfw.
