### ISSUE TITLE
Provide templates for the lazy asses.

### ISSUE THREAD

**Issue by jtagcat** [KeenRivals/bestmotherfucking.website#43]
```
Templates for the lazy asses.
Seriously, how hard is to make your website _a_ good motherfucking website? Don't delay, use these templates today:
 - Hugo
 - Jekyll
 - WP
 - 11ty
 - whatever you can think off
```

Getting people over the fence with 'So I have to redo my entire website? How do I apply this?' with click, click, click. As with everything, making it convenient gets people to actually incorporate/use the 'design' (piracy, security, privacy are quite examples).

**Comment by KeenRivals** [comment]
I think it's a good idea. I don't use any of those platforms though. I'm more of a Pelican guy.

**Comment by jtagcat** [comment]
I can probably do the Hugo one. I made [like 10 PRs](https://github.com/nanxiaobei/hugo-paper/pulls) to the theme paper, but imo it's already too clunked up.

My main question would be how would a collection of posts be displayed? The first thing that comes to mind is this:

```
**Title**
Author · YYYY-MM-DD

Summary, or if not available, first x sentances unless, capped at x characters taken to the nearest end of word.
***
**Title**
Author · YYYY-MM-DD

You get the point. This is the bestmotherfucking.blog
```

Theme names need to be coordinated, something like `best-mother-fucking-hugo-theme`.

**Comment by ghost** [comment]
literally just googled `best-mother-fucking-hugo-theme`, and got
https://hugomodo.github.io/themes/best-motherfucking-website/

**Comment by jtagcat** [comment]
^ is not even a good motherfucking website, garbage.

https://github.com/hell-hunt/BMFW, bit opinionated and tailored for what I'm doing, yet still something.
