### ISSUE TITLE
Linking to doesmysiteneedhttps.com?

### ISSUE THREAD

**Issue by jtagcat** [KeenRivals/bestmotherfucking.website#53]
https://doesmysiteneedhttps.com probably has the same target audience.

Find a way to somehow magically link it?

**Comment by jtagcat** [comment]
Most of the questions 'HTTPS doesn't' can be answered with 'Non-HTTPS does not as well'…

**Comment by ghost** [comment]
You don't unless you're using some shitty JS framework with 400 CVEs. Shitty cope website

**Comment by KeenRivals** [comment]
I don't think I'll link to the site. I think the answer is always yes and by this point it should be obvious.
