### ISSUE TITLE
Site unreachable: missing DNS records

### ISSUE THREAD

**Issue by Seirdy** [KeenRivals/bestmotherfucking.website#58]
The site's A/AAAA/CAA DNS records seem missing, so the host cannot be resolved. This website is currently unreachable.

**Comment by KeenRivals** [comment]
Looks like I broke it when I set up dnssec incorrectly a bit ago. Thank you for letting me know!

**Comment by KeenRivals** [comment]
Should be good now. Reopen if you continue to see problems.
