### ISSUE TITLE
The word "Design" needs to be in scare-quotes, or replaced with the word "aesthetics".

### ISSUE THREAD

**Issue by Lashriel** [KeenRivals/bestmotherfucking.website#68]
See title. When you use the word "design", it gives an impression that design is only about how the website looks. This is not the case, or at least it _shouldn't_ be - so we should be making that clear by either denoting deliberate misuse via scare-quotes, or changing the word used to one that _does_ mean no more than "what the website looks like on the design computer".

Yes, this is about as satirical as the website itself.

**Comment by KeenRivals** [comment]
I think I see what you're getting at but this feels like arguing against the use of the word "theory" in common parlance in favor of "hypothesis". You're correct but this site is about html/css pedantry instead of lexicographical pedantry.
