### ISSUE TITLE
Stop using Apache

### ISSUE THREAD

**Issue by sweepies** [KeenRivals/bestmotherfucking.website#7]
Seriously. It sucks.

Nginx is wildly faster and can handle literally dozens more connections (ESPECIALLY for pure static HTML), while also being way easier to configure.

https://help.dreamhost.com/hc/en-us/articles/215945987-Web-server-performance-comparison

**Comment by KeenRivals** [comment]
I'm a fan of NGINX too! Sites I host myself tend to run NGINX. This site is hosted by NearlyFreeSpeech.net. They only offer Apache hosting. They are extremely cheap for static hosting. This site and another more popular one have cost me a total of 50 cents this year in hosting. I like that I don't have to manage it other than rotating the TLS certificate.

I know it's possible to use some free VPS provider to set up a basic host. But my time is not free and I doubt a free-tier VPS could handle load as well as NearlyFreeSpeech.net—even on NGINX.

**Comment by sweepies** [comment]
Ah I see, why not use GitHub Pages? They offer free TLS too IIRC.

That way, changes to the branch will automatically update the site.

**Comment by KeenRivals** [comment]
They don't support the [caching directives](https://github.com/KeenRivals/bestmotherfucking.website/blob/master/.htaccess#L1) I use and IIRC they don't support forcing HTTPS use via redirect or setting the [HTTP Strict-Transport-Security header](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) (which admittedly I do with Cloudflare instead of at NearlyFreeSpeech.net).

**Comment by sweepies** [comment]
Ah, can't you just put GH Pages behind CloudFlare and just set it to cache everything though?

**Comment by KeenRivals** [comment]
Cloudflare's cache directives are a little stupid. My host serves up 1 week expires headers, but CF won't cache text/html without a Page Rule to tell it to (which I have). I guess I could make it work with GH Pages but NearlyFreeSpeech works well enough. A migration to GH Pages is something I might consider in the future if NFS gives me any trouble.

**Comment by sweepies** [comment]
Yeah, NFS seems pretty good, just disappointing that shared hosts don't offer NGINX :P

**Comment by mahesh-hegde** [comment]
Use a static server like darkhttpd?
