### ISSUE TITLE
I bought all of 19 inches of screen, why are you wasting two thirds of it?

### ISSUE THREAD

**Issue by calimeroteknik** [KeenRivals/bestmotherfucking.website#75]
Yes, I am protesting `max-width` here. It sucks.

I have a solution. It's here: [optionalmargins.html](https://github.com/KeenRivals/bestmotherfucking.website/files/12922106/optionalmargins.html.txt). Click the big-ass margin. I know, it's genius.

I hope we can put the max-width debate to rest. My personal opinion is that users can resize their browser window if they want to, but I'm willing to compromise with the above solution.
In case this cannot be resolved peacefully, have my adblocker ready to filter all of them stinky max-width rules.

**Comment by calimeroteknik** [comment]
Whoops, I woke up and got a ping that it was badly hacked together, here's everything fixed: [fuckingwebsite.html](https://github.com/KeenRivals/bestmotherfucking.website/files/12925527/fuckingwebsite.html.txt)

**Comment by KeenRivals** [comment]
The implementation is kind of clever but I disagree with the sentiment.

**Comment by calimeroteknik** [comment]
In retrospect, I had missed the irony:
>You take a fucking [masterpiece](http://motherfuckingwebsite.com/) and incrementally [ruin](http://bettermotherfuckingwebsite.com/) it for the sake of design.

…indeed, that's exactly what these derivatives do with `max-width`. Well played.


If you were serious though, we have an actual debate. Do you think people are incapable of either resizing their window or clicking reader mode?  
I'm also interested in a serious answer to my 'why' question in the title of this issue.
